config/routes.rb
class BlacklistConstraint
  def initialize
    @ips = ['127.0.0.1']
  end

  def matches?(request)
    @ips.include?(request.remote_ip)
  end
end

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  root 'articles#index'
  resources :articles, shallow: true do
    resources :comments
    collection do
      get 'preview'
    end
  end
  get '*path', to: 'blacklists#index', constraints: BlacklistConstraint.new
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title,
            presence: true,
            length: { minimum: 5 }

  validates :description, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index
    @articles = Article.all

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @articles }
    end
  end

  def new
    Rails.logger.debug request.variant
  end

  def create
    @article = Article.new(article_params)

    if @article.valid?
      @article.save!

      redirect_to @article
    else
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      Rails.logger.debug @article.errors
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])

    @article.destroy

    redirect_to articles_path
  end

  def preview
    render plain: 'aaaa'
  end

  private

  def article_params
    permitted = params.require(:article).permit(:title, :description, :publish)

    if permitted[:publish]
      permitted[:published_at] = DateTime.now

      permitted.delete(:publish)

    end
    permitted
  end
end

app/controllers/blacklists_controller.rb
# frozen_string_literal: true

class BlacklistsController < ApplicationController
  def index
    render plain: 'You are blacklisted'
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def index
    @article = Article.find(params[:article_id])

    render template: 'articles/show'
  end

  def create
    @article = Article.find(params[:article_id])

    @comment = @article.comments.build(comment_params)

    if @comment.valid?
      @comment.save!

      redirect_to @article
    else
      render 'articles/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    @comment.destroy

    redirect_to @comment.article
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/graphql_controller.rb
# frozen_string_literal: true

class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = BlogSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?

    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: :internal_server_error
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
  def present(model)
    klass = "#{model.class}Presenter".constantize
    presenter = klass.new(model, self)
    yield(presenter) if block_given?
  end
end

app/helpers/blacklists_helper.rb
# frozen_string_literal: true

module BlacklistsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <% if @article and @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, 'error') %> prohibited this article from being saved
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :publish %>
    <%= form.check_box :publish %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit <%= @article&.title %></h1>

<%= render 'form' %>

app/views/articles/index.html.haml
%h1
  Articles
  %small= link_to('New', new_article_path)

%div
  %table{ border: "1"}
    %tr
      %th Title
      %th>Description

    - @articles.each do |article|
      %tr
        %td= article.title
        %td= article.description
        %td= link_to('Show', article_path(article))

app/views/articles/new.html.erb
<h1>Create New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<% present(@article) do |a| %>
  <div>
    <h1>
      <%= a.title %> <small>Published At: <%= a.publish_date  %></small>
    </h1>
    <div>
      <p>
        <%= a.description %>
      </p>
    </div>
  </div>
  <div>
    <h2>Comments</h2>
    <div>
      <%= render a.comments %>
    </div>
  </div>
  <div>
    <h2>Add a Comment</h2>
    <div>
      <%= render 'comments/form' %>
    </div>
  </div>
  <div>
    <p>
      <%= link_to 'Edit', edit_article_path(a) %>
    </p>
    <p>
      <%= link_to 'Delete', article_path(a), method: :delete, data: { confirm: 'Are you sure' } %>
    </p>
    <p>
      <%= link_to 'Back', articles_path %>
    </p>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter: </strong>
  <%= comment.commenter %>
</p>
<p>
  <strong>Comment: </strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @article.comments.build], local: true) do |form| %>
  <% if @comment and @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, 'error') %> prohibited this comment from being saved
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :commenter %>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>